name: windows-demo
description: Build windows-demo for windows

runs:
  using: "composite"
  steps:
    - uses: extractions/setup-just@v1
    - name: Install toolchain
      shell: bash
      run: just default-toolchain
    - uses: Swatinem/rust-cache@v1
    - name: Install SQLite
      shell: powershell
      run: choco install sqlite -y --params "/NoTools"
    - name: Build SQLite lib
      shell: powershell
      run: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Tools\MSVC\17.2.32505.173\bin\Hostx64\x64\lib.exe' /DEF:C:\ProgramData\chocolatey\lib\SQLite\tools\sqlite3.def /OUT:C:\ProgramData\chocolatey\lib\SQLite\tools\sqlite3.lib /MACHINE:x64
    - name: Add SQLite lib to path
      shell: bash
      run: echo "C:\ProgramData\chocolatey\lib\SQLite\tools" >> $env:GITHUB_PATH
    - name: Build
      shell: bash
      run: cargo build -p maplibre-demo --target x86_64-pc-windows-msvc
    #- name: Check
    #  shell: bash
    #  run: just check maplibre-demo x86_64-pc-windows-msvc
    - uses: actions/upload-artifact@v3
      with:
        name: maplibre-x86_64-windows-demo
        path: target/x86_64-pc-windows-msvc/debug
        if-no-files-found: error