name: Demo

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  #build-mac:
  #  runs-on: macOS-11
  #  steps:
  #    - uses: actions/checkout@v2
  #    - uses: ./.github/actions/macos-demo
  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/windows-demo