name: Linux demo

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  build-linux-demo:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/linux-demo